Repository rbebb/LANWeather, pull requests merged in 2020-04, with the labels that each got.

#52 22 sensor daemon
  arduino/temp_sensor.ino
  tempsensor/makefile
  tempsensor/sensor_daemon.cpp
  tempsensor/sensor_daemon.hpp
  tempsensord/makefile
  tempsensord/sensor_daemon.cpp
Labels: Drivers, Dæmon

#55 Properly staged file/directory deletion
  tempsensor/makefile
  tempsensor/sensor_daemon.cpp
  tempsensor/sensor_daemon.hpp
Labels: Bug, Other/Needs Definition

#56 12 zmq sensor data
  lanweatherd/src/main.cpp
  lanweatherd/src/sensor_loop.cpp
  lanweatherd/src/sensor_loop.h
  tempsensord/makefile
  tempsensord/sensor_daemon.cpp
Labels: Dæmon, UC-1

#53 25 daemon installation
  lanweatherd/.gitignore
  lanweatherd/lanweatherd.service
  lanweatherd/makefile
  lanweatherd/readme.md
  lanweatherd/src/main.cpp
  lanweatherd/src/sensor_loop.cpp
Labels: Dæmon

#57 Fxied issues sending data over ZMQ
  tempsensord/sensor_daemon.cpp
Labels: Bug

#58 Major Overhaul of the App
  androidapp/.idea/misc.xml
  androidapp/app/build.gradle
  androidapp/app/src/main/java/com/example/lanweather/MainActivity.kt
  androidapp/app/src/main/java/com/example/lanweather/NotificationPublisher.kt
  androidapp/app/src/main/java/com/example/lanweather/data/AppDatabase.kt
  androidapp/app/src/main/java/com/example/lanweather/data/DataConverter.kt
  androidapp/app/src/main/java/com/example/lanweather/data/entity/DailyEntity.kt
  androidapp/app/src/main/java/com/example/lanweather/data/entity/HourlyEntity.kt
  androidapp/app/src/main/java/com/example/lanweather/data/entity/PeriodEntity.kt
  androidapp/app/src/main/java/com/example/lanweather/data/entity/WeatherEntity.kt
  androidapp/app/src/main/java/com/example/lanweather/data/model/Current.kt
  androidapp/app/src/main/java/com/example/lanweather/data/model/Daily.kt
  androidapp/app/src/main/java/com/example/lanweather/data/model/Hourly.kt
  androidapp/app/src/main/java/com/example/lanweather/data/model/Json.kt
  androidapp/app/src/main/java/com/example/lanweather/data/model/Nws.kt
  androidapp/app/src/main/java/com/example/lanweather/data/model/Period.kt
  androidapp/app/src/main/java/com/example/lanweather/data/model/Sensor.kt
  androidapp/app/src/main/java/com/example/lanweather/data/model/Weather.kt
  androidapp/app/src/main/java/com/example/lanweather/ui/forecast/ForecastFragment.kt
  androidapp/app/src/main/java/com/example/lanweather/ui/home/HomeFragment.kt
  androidapp/app/src/main/res/layout/activity_main.xml
  androidapp/app/src/main/res/layout/card_day_overview.xml
  androidapp/app/src/main/res/layout/card_seven_day_forecast.xml
  androidapp/app/src/main/res/layout/card_tomorrow_overview.xml
  androidapp/app/src/main/res/layout/home_fragment.xml
  androidapp/app/src/main/res/values/strings.xml
  androidapp/build.gradle
Labels: App

#61 README Updated
  README.md
  lan_weather_icon.png
Labels: Documentation
